model: file # one_state, five_state, gridworld, file
# if using gridworld, specify the gridworld env name
# MiniGrid-SimpleCrossingS11N5-v0 MiniGrid-Empty-8x8-v0 MiniGrid-Empty-8x8-v0 MiniGrid-LavaGapS7-v0
env: MiniGrid-LavaCrossingS11N5-v0 # MiniGrid-LavaGapS7-v0 MiniGrid-FourRooms-v0
map_path: /workspace/rochan/courses/RL/oprl/maps/maze.txt # /workspace/rochan/courses/RL/oprl/maps/wall.txt
gamma: 0.9

init: # How to initialize values (opt(1)/pes(-1)/zero/rand)
  Q: zero
  V: zero

value_iteration_theta: 0.00001

# number of times to repeat Q learning algos due to randomness in e-greedy policy
exp:
  repeat: 50

q_learning:
  steps: 2000 # episodes
  alpha: 0.05
  epsilon: 0.9
  decay: 0.99
  interval: 20

dq_learning:
  steps: 2000
  alpha: 0.05
  epsilon: 0.9
  decay: 0.99
  interval: 20

pessimistic_q_learning:
  steps: 2000
  alpha: 0.05
  epsilon: 0.9
  decay: 0.99
  interval: 20
  pessimism_coeff: 0.1
