# Perform plotting for experiments
# algo options: ('val_iter', 'q', 'dq', 'pq', 'mmq', 'meanvar', 'mmbq', 'mmbqv2')

perform: ['cum_r', 'bandit']
fmt: png # pdf/png

# rewards plot
cum_r:
  algos: ['mmbq_v2']
  smooth: True
  std_factor: 0.1

q_vals:
  algos: ['val_iter', 'q']

v_vals:
  algos: ['val_iter']

visits:
  algos: ['q', 'dq']
  s_a: [1, 2]

bandit:
  algos: ['mmbqv2', 'mmbq']
  q: True
  select: True